package com.mygdx.isometricgame1;

public enum FacingDirection {
    NORTH, NORTHER_EAST, NORTHEAST, EASTER_EAST, EAST, SOUTHER_EAST, SOUTHEAST, EASTER_SOUTH, SOUTH, SOUTHER_WEST,
    SOUTHWEST, WESTER_SOUTH, WEST, NOTHER_WEST, NORTHWEST,
}
